### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by vielmetti** [cutenode/delice#2]
I'm trying to check the licenses for `node-red`, which I've installed in /usr/lib/node_modules/node-red (with `npm install -g`. And I'm getting this
somewhat mysterious error message.

It looks like `yargs` has the problem.

```
emv@DESKTOP-L7STI4S:~$ delice /usr/lib/node_modules/node-red
/usr/lib/node_modules/delice/node_modules/yargs/yargs.js:1163
      else throw err
           ^

TypeError: Cannot read property 'type' of undefined
    at parse (/usr/lib/node_modules/delice/node_modules/liblice/lib/parseLicense.js:15:52)
    at /usr/lib/node_modules/delice/node_modules/liblice/exports/modules.js:12:20
    at Array.forEach (<anonymous>)
    at buildObjectExport (/usr/lib/node_modules/delice/node_modules/liblice/exports/modules.js:10:27)
    at buildObjectLicenseReport (/usr/lib/node_modules/delice/node_modules/liblice/exports/licenses.js:4:16)
    at buildPrettyPrint (/usr/lib/node_modules/delice/commands/default.js:29:27)
    at Object.exports.handler (/usr/lib/node_modules/delice/commands/default.js:25:3)
    at Object.runCommand (/usr/lib/node_modules/delice/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/usr/lib/node_modules/delice/node_modules/yargs/yargs.js:1087:28)
    at Object.get [as argv] (/usr/lib/node_modules/delice/node_modules/yargs/yargs.js:1012:21)
```

**Comment by vielmetti** [comment]
This is no longer important to me, and since it was not addressed this decade, I will close it. Please reopen if you still find it important.
