### ISSUE TITLE
Error resolving dependency (?)

### ISSUE THREAD

**Issue by Fishrock123** [cutenode/delice#6]
```bash
$ delice
/Users/Jeremiah/npm/lib/node_modules/delice/node_modules/yargs/yargs.js:1163
      else throw err
           ^

Error: ENOENT: no such file or directory, stat 'node_modules/.bin/detect-libc'
    at Object.statSync (fs.js:856:3)
    at /Users/Jeremiah/npm/lib/node_modules/delice/node_modules/liblice/lib/recursiveFileSearch.js:7:55
    at Array.filter (<anonymous>)
    at getFilePaths (/Users/Jeremiah/npm/lib/node_modules/delice/node_modules/liblice/lib/recursiveFileSearch.js:7:32)
    at /Users/Jeremiah/npm/lib/node_modules/delice/node_modules/liblice/lib/recursiveFileSearch.js:9:64
    at Array.reduce (<anonymous>)
    at getFilePaths (/Users/Jeremiah/npm/lib/node_modules/delice/node_modules/liblice/lib/recursiveFileSearch.js:9:29)
    at /Users/Jeremiah/npm/lib/node_modules/delice/node_modules/liblice/lib/recursiveFileSearch.js:9:64
    at Array.reduce (<anonymous>)
    at getFilePaths (/Users/Jeremiah/npm/lib/node_modules/delice/node_modules/liblice/lib/recursiveFileSearch.js:9:29) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'node_modules/.bin/detect-libc'
}
```

Looks like some dependency this module needs is unmet? Maybe?

**Comment by bnb** [comment]
AFAIK it doesn't seem to be that. This error is referring to [code in liblice](https://github.com/cutenode/liblice/blob/master/lib/recursiveFileSearch.js#L7) that works and exists. It walks the `node_modules` on disk rather than doing network requests, so my guess is that something in your `node_modules` at the location specified in the `path` of that error output (last line) is tripping up that functionality. 

For reference, it doesn't currently seem like `detect-libc` is in the dep tree:
```
$ npm ls detect-libc

delice@1.0.2 /Users/cyren/GitHub/delice
└── (empty)
```

Would you be able to share whatever is in your `node_modules/.bin/detect-libc` and – if at all possible – how that's introduced?

**Comment by Fishrock123** [comment]
`node_modules/.bin/detect-libc` is `ENOENT`. It does not exist.

The project I am running this on certainly does not need to detect `libc` and neither should `delice`.

**Comment by Fishrock123** [comment]
```
$ npm ls detect-libc
ncm-cli@1.3.4 /Users/Jeremiah/Documents/nodesource/ncm-cli
└── (empty)
```

You can try it on that repository if you'd like. https://github.com/nodesource/ncm-cli

**Comment by bnb** [comment]
FWIW this should be fixed in liblice@3.0.0 which just shipped. Need to update delice still, but hoping to do that soonish :)
